FROM python:latest

COPY . /app/nlp

WORKDIR /app/nlp

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# docker build -t nlpfastapi .
# docker run -itd -p 3000:3000 -v .:/app/nlp nlpfastapi /bin/bash